let handler  = async (m, { conn }) => {
let sad = [
  "Tiba-tiba aku merasa tidak nyaman berada di mana pun. Entah itu di sekolah atau di rumah. Dan aku pun merasa orang-orang di sekitarku menjadi orang asing. Bahkan, aku merasa asing dengan diriku sendiri",
  "Sakit sekali rasanya ketika Anda sudah melakukan yang terbaik, tapi ternyata masih tidak cukup.",
  "Salah satu perlindungan dari kekecewaan adalah memiliki kesibukan.",
  "Jangan khawatir akan hari esok kesusahan hari ini cukuplah hari ini.",
  "Orang menangis bukan karena mereka lemah. Tapi, mereka menangis karena telah berusaha kuat dalam waktu yang lama.",
  "Ketika kamu bersedih karena cinta, percayalah Tuhan telah menitipkan obat penawar luka di tangan seseorang.",
  "Terkadang senyuman menjadi pilihan terbaik disaat rasa sedih tak bisa dijelaskan dengan kata-kata.",
  "Di saat tak ada seseorang yang bersedia memberikan pundaknya untuk tempat kamu mencurahkan kesedihan, hanya doa’lah yang mampu mengurangi kepedihanmu.",
  "Tidakkah menyedihkan ketika kamu tersakiti, namun hanya bisa berkata, aku sudah terbiasa.",
  "Rasa kecewa yang menumpuk bahkan bisa membuat orang menjadi gila.",
  "Sulit untuk menggambarkan senyum ketika hati ini sedang menangis.",
  "Jika ada seseorang yang mengajakmu ke puncak, maka ia adalah aku yang paling depan untuk menemanimu mendaki,",
  "Embun telah pergi di pagi ini, basah hujan semalam pun telah mengering. Namun ketika ku lihat perjuangan di balik cermin, maka yang tersisa hanyalah kenangan.",
  "Meski tak bisa ku sentuh, namun aku inginkan kamu yang utuh.",
  "Sebesar itukah ombak kenanganmu hingga kau anggap kesungguhan ini hanyalah sebesar semut yang ingin hidup di samudra.",
  "Tak usahlah kau merasa terganggu, karena aku hanya mencintaimu dalam diam.",
  "Entah kenapa saat ia menghilang, seluruh dunia menjadi terpuruk.",
  "Sungguh hebat sekali, baru kemarin kita jalan bersama, sekarang kau dengan yang lain.",
  "Aku tak pernah berharap agar kau menjadi milikku, namun hanya satu pintaku. Tersenyumlah dan berkata jika kita bertemu – Ia adalah orang yang selalu sayang padaku.",
  "Orang-orang bahkan tidak menyadari akan kesepian ini, dan seakan-akan mereka menganggap remeh semua ini,",
  "Saat hujan, carilah pelangi. Saat gelap, cari bintang.",
  "Rintangan seringkali merupakan batu loncatan.",
  "Tidak apa-apa menjadi tongkat cahaya. Kadang kita harus istirahat sebelum kita bisa bersinar.",
  "Terkadang kita diuji. Bukan untuk menunjukkan kelemahan kita, tapi untuk menemukan kekuatan kita.",
  "Lepaskan pikiran yang tidak membuatmu kuat.",
  "Jadilah seperti angin. Bawalah semuanya bersamamu dan kemudian tenanglah.",
  "Hal terpenting adalah menikmati hidupmu menjadi bahagia.",
  "Selalu maafkan musuhmu; tidak ada yang begitu mengganggu mereka.",
  "Banyak hal berubah. Dan teman-teman pergi. Hidup tidak berhenti untuk siapa pun.",
  "Jika kamu tidak menyukai jalan yang kamu lalui, mulailah mencoba jalan yang lain.",
  "Hidup tidak memiliki kewajiban untuk memberi kita apa yang kita harapkan.",
  "Rahasia kehidupan adalah jatuh tujuh kali dan bangun delapan kali.",
  "Kemanapun kau pergi, tak peduli dalam cuaca apa pun, selalu bawa sinar mataharimu sendiri.",
  "Aku baru menyadari bahwa jika kau mencintai kehidupan, hidup akan balik mencintaimu.",
  "Ketika kau berhenti berharap orang lain menjadi sempurna, kau akan bisa menyukai mereka apa adanya.",
  "Ku kira aku candumu ternyata aku hanyalah candamu",
  "Bila yang datang dapat pergi apakah yang pergi dapat kembali?",
  "Kukira aku satu satunya ternyata salah satunya",
  "Sekedar peran pengganti di saat pemeran utama tidak ada",
  "Kamu tidak dapat menemukan kedamaian dengan menghindari kehidupan.",
  "Dia yang wajahnya tidak bersinar, tidak akan pernah menjadi bintang.",
  "Orang menangis bukan karena mereka lemah. Tapi, mereka menangis karena telah berusaha kuat dalam waktu yang lama.",
  "Cintai hidup yang kamu jalani. Jalani hidup yang kamu cintai. ",
  "Orang-orang berkata untuk mengikuti hati. Aku melakukannya, tapi hatiku malah terluka.",
  "Hal yang paling sulit adalah ketika kita mencintai seseorang yang mencintai orang lain.",
  "Kau menjadi penenang bagi hatiku sekaligus jadi bagian yang membingungkan.",
  "Manisnya cinta kita semanis madu. Namun sayangnya, madu itu telah kau bagi tiga. Dan sayangnya, hubungan kita pun harus putus.",
  "Ketidakbisaan hanya dimiliki orang-orang yang gagal. Tidak pernah ada kata kata tidak bisa, walau harus sejuta kali mencoba dan galau.",
  "Tak pernah ada kata menyesal untuk mencintaimu. Namun, yang paling aku sesalkan adalah hubungan kita yang tak bisa dilanjutkan. Maaf ku pilih putus dan aku tak akan pernah melupakanmu karena kamu pernah menjadi orang yang mengisi hari-hari indahku.",
  "Cinta layak diperjuangkan, tetapi ia tidak berarti apa-apa jika yang berusaha hanya seorang saja.",
  "Kupikir kau masih mencintaiku, tapi kita tak bisa melepas kenyataan bahwa aku tak cukup untukmu.",
  "Betapa anehnya, setelah semua ini kita kembali menjadi orang asing.",
  "Lebih baik mengakhiri hubungan lebih cepat daripada terlambat. Kamu tak akan pernah menghabiskan setiap hari, setiap minggu, dan setiap tahun bersama orang yang tak benar-benar mencintaimu kembali.",
  "Dengarkan hatimu sebelum kamu mengucapkan selamat tinggal padanya.",
  "Ada sakit yang tidak bisa dijelaskan dan ada kecewa yang tidak bisa diungkapkan",
  "Aku tahu hatiku tak akan pernah sama. Tapi aku mencoba meyakinkan diriku sendiri bahwa aku baik baik saja.",
  "Aku masih mencintainya, dan ini adalah hal terburuk. Aku menginginkannya kembali.",
  "Kita berdua tahu, bahwa aku bukanlah yang kamu butuhkan.",
  "Aku tahu, seorang laki laki seharusnya tidak menangis. Tapi aku tak bisa menahan air mata ini.",
  "Tapi, jangan kau pikir aku akan terpuruk lantaran patah hati. Aku terlalu kuat untuk hal semacam ini.",
  "Berjalan sendiri bukanlah hal yang sulit. Namun, bila kita telah berjalan sedemikian jauh dengan seseorang dalam suatu hubungan lalu kembali ke titik awal seorang diri, itulah bagian yang tersulit.",
  "Hal yang paling sulit dalam hidup ini adalah melepaskan seseorang yang sangat kamu cintai.",
  "Terkadang aku berharap aku menjadi anak kecil lagi. Lutut yang terluka lebih mudah diobati daripada hati yang terluka.",
  "Bagaimana pun kita sudah menjalani semua itu. Biarlah segalanya menjadi kenangan. Suatu hari nanti kita akan melupakan.",
  "Ada waktu untuk berangkat, meski tidak ada tempat pasti untuk pergi.",
  "Menangis sendiri tidak menunjukkan bahwa kamu lemah, tetapi itu menunjukkan bahwa kamu kuat.",
  "Menyedihkan mengetahui bahwa saya sudah selesai. Tapi, melihat ke belakang, saya punya banyak kenangan indah.",
  "Beberapa hari hanyalah hari yang buruk, itu saja. Kamu harus mengalami kesedihan untuk mengetahui kebahagiaan, dan saya mengingatkan diri saya sendiri bahwa tidak setiap hari akan menjadi hari yang baik, begitulah adanya!",
  "Jangan pernah membandingkan dirimu dengan orang lain karena mereka tidak tahu saat burukmu dan kamu tidak tahu tentang mereka.",
  "Biarlah jiwaku tersenyum melalui hatiku dan hatiku tersenyum melalui mataku agar aku dapat menyebarkan senyuman yang kaya di dalam hati yang sedih.",
  "Hal-hal yang menyedihkan terjadi. Tapi, kita tidak perlu hidup sedih selamanya.",
  "Air mata yang menetes untuk orang lain bukanlah pertanda kelemahan. Itu adalah tanda hati yang murni.",
  "Kamu tidak pernah bisa mengontrol dengan siapa kamu jatuh cinta, bahkan ketika kamu berada di saat yang paling menyedihkan dan membingungkan dalam hidupmu. Kamu tidak jatuh cinta dengan orang lain karena mereka menyenangkan. Itu terjadi begitu saja.",
  "Banyak hal berubah. Dan teman-teman pergi. Hidup tidak berhenti untuk siapa pun.",
  "Orang akan melihat kesuksesanmu, tetapi mereka tidak akan melihat perjuanganmu.",
  "Kesedihan juga merupakan salah satu bentuk pembelaan.",
  "Daripada menangis dan mendambakan mereka yang meninggalkan jalan kita selama saat-saat gelap dalam hidup kita, mari luangkan waktu untuk berterima kasih kepada mereka yang berdiri dan membantu kita melewati jalan gelap itu.",
  "Setiap orang memiliki rahasia dukacita yang tidak diketahui dunia; dan sering kali kita menyebut orang yang dingin, padahal dia hanya sedih.",
  "Saat-saat indah hari ini adalah saat-saat sedih di masa depan.",
  "Air mata adalah kata-kata yang perlu dituliskan.",
  "Hidup itu sulit, kamu harus kuat dari dalam.",
  "Jika Anda adalah orang yang berhati baik, Anda mengalami lebih banyak masalah daripada yang lain.",
  "Hal yang paling menyakitkan adalah kehilangan diri sendiri dalam proses terlalu mencintai seseorang, dan lupa bahwa kamu juga spesial.",
  "Pertama, terimalah kesedihan. Sadarilah bahwa tanpa kalah, menang tidaklah terlalu bagus.",
  "Don't put the sadness on your face because you never know that there is someone who feels happy by your smile.",
  "The one who gives you happiness that you can not explain will always be a reason of your sadness that you can not explain.",
  "God always has the best one for you. He has the solution for your every problem, relieving feeling for your sadness, and happiness that waits for you.",
  "The only things why sadness is so cruel and hurting me is just because you are the person who stand on there.",
  "He can give you everythings of materials and stuffs you need everyday which can not be explained, but the reason of love is also can not be as much as he give you.",
  "I know i am not so meaningful when you cried on your sadness, when you screamed on the public, when you hate everybody. But this is me who always do everything as human who always love you.",
  "When i was kid i would be a police man so i could caught the bad person. When i was teenager i would be a manager so i have much money. When i am adult, i realized that i am not anything which was on my mind.",
  "The deepest pain is unseen by eyes. The deepest sadness is unsaid by words.",
  "Sometimes i choose to look happy because i do not want to explain why i am sad to them who even can not understand what i feel.",
  "As God said just believe in me, lift your hands and i will help you.",
  "This life is a choice like a quiz. Whatever makes you sad, throw it away. And, whatever makes you smile, keep it in your hand.",
  "Pleasure of love lasts but a moment. Pain of love lasts a lifetime.",
  "I have a thousand reasons to stick with you. However, you have a thousand reasons to leave me.",
  "We started with a simple hello but ended with a complicated goodbye.",
  "I wish I could hurt you the way you hurt me. But I know that if I had the chance, I wouldn't do it.",
  "The deepest pain is unseen by eyes. The deepest sadness is unsaid by words.",
  "You taught me how to love, but not how to stop.",
  "You broke my heart. But I still love you with all the pieces.",
  "Giving up, doesn't mean you are weak, sometimes it means that you are strong enough to let go.",
  "Sometimes I wish I were a little kid again, skinned knees are easier to fix than broken hearts",
  "The hottest love has the coldest end",

]
let diaa = sad[Math.floor(Math.random() * sad.length)]
  conn.reply(m.chat,`“${diaa}”`, m)
}
handler.help = ['sad']
handler.tags = ['quotes']
handler.command = /^(sad)$/i
handler.owner = false
handler.mods = false
handler.premium = false
handler.group = false
handler.private = false
handler.limit = false
handler.admin = false
handler.botAdmin = false

handler.fail = null

module.exports = handler